# Generated by Django 5.2.17 on 2026-08-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='medium', max_length=16)),
                ('category', models.CharField(choices=[('responsive', 'Responsive'), ('layout', 'Layout'), ('spacing', 'Spacing'), ('typography', 'Typography'), ('color', 'Color'), ('accessibility', 'Accessibility'), ('navigation', 'Navigation'), ('interaction', 'Interaction'), ('performance', 'Performance'), ('ux', 'UX')], db_index=True, default='responsive', max_length=16)),
                ('source', models.CharField(choices=[('deterministic', 'Deterministic'), ('accessibility', 'Accessibility'), ('ai', 'AI'), ('combined', 'Combined')], default='deterministic', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('selector', models.CharField(blank=True, max_length=500)),
                ('viewport_width', models.IntegerField(blank=True, null=True)),
                ('viewport_height', models.IntegerField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('ai_explanation', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='scans.scan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scan', 'severity'], name='issues_issu_scan_id_e6f1aa_idx'), models.Index(fields=['scan', 'category'], name='issues_issu_scan_id_22519f_idx')],
            },
        ),
    ]
