# Generated by Django 5.2.17 on 2026-08-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.CharField(blank=True, max_length=64)),
                ('new_value', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('improved', 'Improved'), ('failed', 'Failed')], db_index=True, default='failed', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('screenshot_before', models.CharField(blank=True, max_length=500)),
                ('screenshot_after', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
