# Generated by Django 5.2.17 on 2026-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scan_ai_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.PositiveBigIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField()),
                ('pid', models.IntegerField()),
                ('version', models.CharField(default='db-poll-2', max_length=40)),
            ],
            options={
                'db_table': 'worker_heartbeat',
            },
        ),
    ]
