# Generated by Django 5.2.17 on 2026-08-15 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('normalized_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='queued', max_length=16)),
                ('progress_stage', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating URL'), ('launching', 'Launching browser'), ('loading', 'Loading website'), ('capturing', 'Capturing screenshots'), ('responsive', 'Checking responsive layout'), ('accessibility', 'Checking accessibility'), ('ai_analysis', 'Running AI analysis'), ('reporting', 'Building report'), ('complete', 'Complete')], default='queued', max_length=32)),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ai_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewport_width', models.IntegerField()),
                ('viewport_height', models.IntegerField()),
                ('path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='scans.scan')),
            ],
            options={
                'ordering': ['viewport_width', 'viewport_height'],
            },
        ),
        migrations.CreateModel(
            name='PageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewport_width', models.IntegerField()),
                ('viewport_height', models.IntegerField()),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='scans.scan')),
            ],
            options={
                'ordering': ['viewport_width', 'viewport_height', 'key'],
                'constraints': [models.UniqueConstraint(fields=('scan', 'viewport_width', 'viewport_height', 'key'), name='unique_page_metric')],
            },
        ),
    ]
