# Generated by Django 5.2.17 on 2026-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
